POST http://localhost:7800/myapp HTTP/1.1
Content-Type: application/xml
Authorization: Basic myusername:mypassword

<employees>
  <employee>
    <name>Upendra Roul</name>
    <position>Software Developer</position>
    <joinyear>2010</joinyear>
    <salary>6000</salary>
  </employee>
  <employee>
    <name>Jay Prakash</name>
    <position>Testers</position>
    <joinyear>2010</joinyear>
    <salary>7000</salary>
  </employee>
  <employee>
    <name>Rekha Sharma</name>
    <position>HR</position>
    <joinyear>2005</joinyear>
    <salary>7000</salary>
  </employee>
  <employee>
    <name>Rohit S</name>
    <position>House Keeping</position>
    <joinyear>2000</joinyear>
    <salary>3000</salary>
  </employee>
</employees>